apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: dummy-go-app
  namespace: dummy-go-app
spec:
  promotionPolicies:
    - stage: dev
      autoPromotionEnabled: true
    - stage: production
      autoPromotionEnabled: false

