apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: integration-test
  namespace: dummy-go-app
spec:
  metrics:
  - name: integration-test
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: check-color
                image: curlimages/curl:latest
                command:
                - sh
                - -c
                - |
                  curl -sf http://dummy-go-app-podinfo:9898/env | grep -q 'PODINFO_UI_COLOR=#CC562E'
              restartPolicy: Never
          backoffLimit: 1

