apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: dummy-go-app
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: dummy-go-app
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: gitopsRepo
          value: git@github.com:adamplansky/dummy-go-app.git
        - name: srcPath
          value: ./src
        - name: outPath
          value: ./out
        - name: targetBranch
          value: stage/${{ ctx.stage }}
      steps:
        - uses: git-clone
          as: clone
          config:
            repoURL: ${{ vars.gitopsRepo }}
            checkout:
              - commit: ${{ commitFrom(vars.gitopsRepo).ID }}
                path: ${{ vars.srcPath }}
              - branch: ${{ vars.targetBranch }}
                create: true
                path: ${{ vars.outPath }}
        - uses: git-clear
          config:
            path: ${{ vars.outPath }}
        - uses: helm-template
          config:
            path: ${{ vars.srcPath }}/helm-chart
            releaseName: dummy-go-app
            valuesFiles:
              - ${{ vars.srcPath }}/helm-chart/values-${{ ctx.stage }}.yaml
            outPath: ${{ vars.outPath }}/manifests.yaml
        - uses: git-commit
          as: commit
          config:
            path: ${{ vars.outPath }}
            message: "Promoted to ${{ ctx.stage }}"
        - uses: git-push
          config:
            path: ${{ vars.outPath }}
            targetBranch: ${{ vars.targetBranch }}
        - uses: argocd-update
          config:
            apps:
              - name: dummy-go-app-${{ ctx.stage }}
                sources:
                  - repoURL: ${{ vars.gitopsRepo }}
                    desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: dummy-go-app
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: dummy-go-app
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      vars:
        - name: gitopsRepo
          value: git@github.com:adamplansky/dummy-go-app.git
        - name: srcPath
          value: ./src
        - name: outPath
          value: ./out
        - name: targetBranch
          value: stage/${{ ctx.stage }}
      steps:
        - uses: git-clone
          as: clone
          config:
            repoURL: ${{ vars.gitopsRepo }}
            checkout:
              - commit: ${{ commitFrom(vars.gitopsRepo).ID }}
                path: ${{ vars.srcPath }}
              - branch: ${{ vars.targetBranch }}
                create: true
                path: ${{ vars.outPath }}
        - uses: git-clear
          config:
            path: ${{ vars.outPath }}
        - uses: helm-template
          config:
            path: ${{ vars.srcPath }}/helm-chart
            releaseName: dummy-go-app
            valuesFiles:
              - ${{ vars.srcPath }}/helm-chart/values-${{ ctx.stage }}.yaml
            outPath: ${{ vars.outPath }}/manifests.yaml
        - uses: git-commit
          as: commit
          config:
            path: ${{ vars.outPath }}
            message: "Promoted to ${{ ctx.stage }}"
        - uses: git-push
          config:
            path: ${{ vars.outPath }}
            targetBranch: ${{ vars.targetBranch }}
        - uses: argocd-update
          config:
            apps:
              - name: dummy-go-app-${{ ctx.stage }}
                sources:
                  - repoURL: ${{ vars.gitopsRepo }}
                    desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production
  namespace: dummy-go-app
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: dummy-go-app
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      vars:
        - name: gitopsRepo
          value: git@github.com:adamplansky/dummy-go-app.git
        - name: srcPath
          value: ./src
        - name: outPath
          value: ./out
        - name: targetBranch
          value: stage/${{ ctx.stage }}
      steps:
        - uses: git-clone
          as: clone
          config:
            repoURL: ${{ vars.gitopsRepo }}
            checkout:
              - commit: ${{ commitFrom(vars.gitopsRepo).ID }}
                path: ${{ vars.srcPath }}
              - branch: ${{ vars.targetBranch }}
                create: true
                path: ${{ vars.outPath }}
        - uses: git-clear
          config:
            path: ${{ vars.outPath }}
        - uses: helm-template
          config:
            path: ${{ vars.srcPath }}/helm-chart
            releaseName: dummy-go-app
            valuesFiles:
              - ${{ vars.srcPath }}/helm-chart/values-${{ ctx.stage }}.yaml
            outPath: ${{ vars.outPath }}/manifests.yaml
        - uses: git-commit
          as: commit
          config:
            path: ${{ vars.outPath }}
            message: "Promoted to ${{ ctx.stage }}"
        - uses: git-push
          config:
            path: ${{ vars.outPath }}
            targetBranch: ${{ vars.targetBranch }}
        - uses: argocd-update
          config:
            apps:
              - name: dummy-go-app-${{ ctx.stage }}
                sources:
                  - repoURL: ${{ vars.gitopsRepo }}
                    desiredRevision: ${{ outputs.commit.commit }}
